/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 * @description Frame for setting the GUI Font
 * @version 1.0
 * @authors Osvaldo Francisco Barrantes Paniagua
 *          Jose Fabio Ávila Estrada
 */
public class Fuente extends javax.swing.JFrame {
    
    /**
     * Creates new form Fuente
     */
    public Fuente() {
        initComponents();
        generarFuentes();
        generarEstilosDeFuente();
        lsTamaño.setSelectedValue("11", true);
        cambiarMuestra();
    }
    
    /**
     * Obtiene las Fuentes del sistema y las almacena en una lista para 
     * mostrarlas en pantalla.
     */
    private void generarFuentes() {
        GraphicsEnvironment ambienteGráfico = GraphicsEnvironment.
                getLocalGraphicsEnvironment();
        String fuentes[] = ambienteGráfico.getAvailableFontFamilyNames();
        DefaultListModel modeloFuentes = new DefaultListModel();
        for (String fuente : fuentes) {
            modeloFuentes.addElement(fuente);
        }
        lsFuente.setModel(modeloFuentes);
        lsFuente.setSelectedValue("Tahoma", true);
    }
    
    /**
     * Se definen los estilos de Fuente y se almacenan en una lista para 
     * mostrarlos en pantalla.
     */
    private void generarEstilosDeFuente() {
        Object estilos[][] = {
            { new Font("Tahoma", Font.PLAIN, 12), Color.BLACK, "Normal" },
            { new Font("Tahoma", Font.BOLD, 12), Color.BLACK, "Negrita" },
            { new Font("Tahoma", Font.ITALIC, 12), Color.BLACK, "Cursiva" },
            { new Font("Tahoma", Font.BOLD + Font.ITALIC, 12), Color.BLACK, "Cursiva Negrita" }
        };
        DefaultListModel modeloEstiloFuentes = new DefaultListModel();
        for (Object[] estilo : estilos) {
            modeloEstiloFuentes.addElement(estilo);
        }
        lsEstiloFuente.setCellRenderer(new ComplexCellRenderer());
        lsEstiloFuente.setModel(modeloEstiloFuentes);
        lsEstiloFuente.setSelectedIndex(0);
        tfEstiloFuente.setText("Normal");
    }
    
    /**
     * Toma la Fuente, Estilo y Tamaño de letra seleccionados de la GUI y la 
     * refleja en un JLabel.
     */
    private void cambiarMuestra() {
        int tamaño = 11, estilo = lsEstiloFuente.getSelectedIndex();
        
        try {
            tamaño = Integer.parseInt(lsTamaño.getSelectedValue());
        } catch (NumberFormatException ex) {
            
        }
        lbMuestra.setFont(new Font(lsFuente.getSelectedValue(), estilo, tamaño));
    }
    
    /**
     * Clase interna que permite que los estilos se muestren en un JList
     */
    private class ComplexCellRenderer implements ListCellRenderer {
        protected DefaultListCellRenderer defaultRenderer = new DefaultListCellRenderer();

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index,
            boolean isSelected, boolean cellHasFocus) {
            @SuppressWarnings("UnusedAssignment")
            Font theFont = null;
            @SuppressWarnings("UnusedAssignment")
            Color theForeground = null;
            @SuppressWarnings("UnusedAssignment")
            String theText = null;

            JLabel renderer = (JLabel) defaultRenderer.
                    getListCellRendererComponent(list, value, index, isSelected, 
                            cellHasFocus);

            if (value instanceof Object[]) {
                Object values[] = (Object[]) value;
                theFont = (Font) values[0];
                theForeground = (Color) values[1];
                theText = (String) values[2];
            } else {
                theFont = list.getFont();
                theForeground = list.getForeground();
                theText = "";
            }
            if (!isSelected) {
                renderer.setForeground(theForeground);
            }
            renderer.setText(theText);
            renderer.setFont(theFont);
            return renderer;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbMuestra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfFuente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsFuente = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsEstiloFuente = new javax.swing.JList<>();
        tfEstiloFuente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lsTamaño = new javax.swing.JList<>();
        tfTamaño = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bnAceptar = new javax.swing.JButton();
        bnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fuente");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbMuestra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMuestra.setText("Muestra");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 180, 160, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Fuente:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 140, 25);

        tfFuente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfFuente.setEnabled(false);
        getContentPane().add(tfFuente);
        tfFuente.setBounds(10, 25, 140, 30);

        lsFuente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lsFuente.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsFuenteValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lsFuente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 55, 140, 120);

        lsEstiloFuente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lsEstiloFuente.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsEstiloFuenteValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lsEstiloFuente);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(160, 55, 140, 120);

        tfEstiloFuente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfEstiloFuente.setEnabled(false);
        getContentPane().add(tfEstiloFuente);
        tfEstiloFuente.setBounds(160, 25, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Estilo de fuente:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 0, 140, 25);

        lsTamaño.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lsTamaño.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "8", "9", "10", "11", "12", "14", "16", "18", "20", "22", "24", "26", "28", "36", "48", "72" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lsTamaño.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsTamañoValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lsTamaño);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(310, 55, 60, 120);

        tfTamaño.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(tfTamaño);
        tfTamaño.setBounds(310, 25, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tamaño:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 0, 60, 25);

        bnAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnAceptar.setText("Aceptar");
        bnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(bnAceptar);
        bnAceptar.setBounds(180, 180, 90, 30);

        bnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnCancelar.setText("Cancelar");
        bnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bnCancelar);
        bnCancelar.setBounds(280, 180, 90, 30);

        setSize(new java.awt.Dimension(404, 254));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lsTamañoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsTamañoValueChanged
        // Actualiza la caja de texto con el tamaño seleccionado.
        tfTamaño.setText(lsTamaño.getSelectedValue());
        cambiarMuestra();
    }//GEN-LAST:event_lsTamañoValueChanged

    private void bnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCancelarActionPerformed
        // Cierra esta pantalla
        this.dispose();
    }//GEN-LAST:event_bnCancelarActionPerformed

    private void bnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAceptarActionPerformed
        // Captura los datos obtenidos.
        String fuente, estilo, tamaño;
        fuente = tfFuente.getText();
        estilo = tfEstiloFuente.getText();
        tamaño = tfTamaño.getText();
        this.dispose();
    }//GEN-LAST:event_bnAceptarActionPerformed

    private void lsFuenteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsFuenteValueChanged
        // Actualiza la caja de texto con la fuente seleccionada.
        tfFuente.setText(lsFuente.getSelectedValue());
        cambiarMuestra();
    }//GEN-LAST:event_lsFuenteValueChanged

    private void lsEstiloFuenteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsEstiloFuenteValueChanged
        // Actualiza la caja de texto con el estilo de fuente seleccionado.
        Object valorObtenido = lsEstiloFuente.getSelectedValue();
        Object[] estilos = ((Object[]) valorObtenido);
        tfEstiloFuente.setText(estilos[2].toString());
        cambiarMuestra();
    }//GEN-LAST:event_lsEstiloFuenteValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.
                    UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | 
                IllegalAccessException | javax.swing.
                UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fuente.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Fuente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnAceptar;
    private javax.swing.JButton bnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbMuestra;
    private javax.swing.JList<String> lsEstiloFuente;
    private javax.swing.JList<String> lsFuente;
    private javax.swing.JList<String> lsTamaño;
    private javax.swing.JTextField tfEstiloFuente;
    private javax.swing.JTextField tfFuente;
    private javax.swing.JTextField tfTamaño;
    // End of variables declaration//GEN-END:variables
}
